### ISSUE TITLE
CURLFile класс вместо @. $filename

### ISSUE THREAD

**Issue by wshaman** [jumper423/yii2-captcha#1]
Собственно, 
Deprecated: curl_setopt(): The usage of the @filename API for file uploading is deprecated. Please use the CURLFile class instead in vendor/jumper423/yii2-captcha/Captcha.php:150
https://wiki.php.net/rfc/curl-file-upload
По сути, сработало с банальным:
yii2-captcha/Captcha.php: 135

``` php
-'file' =>  '@' . $filename,
+'file' => new \CURLFile($filename),
```

Но по-хорошему бы как-то так

``` php
'file' => (version_compare(PHP_VERSION, '5.5.0') >= 0) ? new \CURLFile($filename):  '@' . $filename,
```

**Comment by jumper423** [comment]
Спасибо, поправил
