### ISSUE TITLE
php 7.0 curl

### ISSUE THREAD

**Issue by wshaman** [jumper423/yii2-captcha#2]
В php7 на CURLOPT_SAFE_UPLOAD такая ругань: 'curl_setopt(): Disabling safe uploads is no longer supported'
Учитывая, что с 5.6 оно уже не принипиально, может стоит в jumper423/yii2-captcha/Captcha.php:146 вообще убрать:

```
        if (version_compare(PHP_VERSION, '5.5.0') >= 0) {
            curl_setopt($ch, CURLOPT_SAFE_UPLOAD, false);
        }
```

Или оставить проверку на 5.5 только, но как по мне это вообще лишено смысла.

**Comment by jumper423** [comment]
Thank you. 7 not tested. I'm gonna fix that.

**Comment by jumper423** [comment]
Эта проверка необходима, так как в php 5.6 параметр CURLOPT_SAFE_UPLOAD стоит по умолчанию как true, что не допустимо для правильной работы.
Залил новую версию, проверьте.
